### ISSUE TITLE
Final Capstone Project - Setup Kanban Board

### ISSUE THREAD

**Issue by HFG43** [HFG43/final_capstone_back_end#12]
⭐Kanban Board - Request a Review 👨‍💻
Project details 📃

Link the Kanban Board: https://github.com/users/HFG43/projects/9

Number of group members: Four (4) members: 
- @NitBravoA92 
- @AndreaM2429 
- @Dachrono 
- @HFG43

Find below a print of our Kanban Board:

![Image](https://github.com/HFG43/final_capstone_back_end/assets/117187653/088eeb78-d6f3-4ad8-98e7-dad5325efe3d)

To the Reviewer
💝 We really thank 🙇‍♂️ you, dear reviewer 👨‍🎨 for dedicating your precious 🥇 time ⌚ to check this Kanban board 🧾 .

We kindly ask 🙏 dear reviewer 🤵 that if there is any kind of issue 🦯 in this Kanban board, please do list 📃 them in a descriptive 💡 manner and give your best suggestions 🎁 if needed.

If you think some issues are essential to be changed ♻️ please kindly contact 📞 us through Zoom or Slack, We are available on Microverse UTC-6 time zone.

**Comment by Meltrust** [comment]
Hi @HFG43,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have been pointed, have descriptions and assignees.  Pointings are fair according to spec.✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by NitBravoA92** [comment]
@Meltrust Thank you so much for taking the time to review our Kanban Board!
