### ISSUE TITLE
[1.5pt] - Define ERD

### ISSUE THREAD

**Issue by HFG43** [HFG43/final_capstone_back_end#2]
Generate diagram considering Associations in the different items for:
-User
-Experience
-Reservation

**Comment by HFG43** [comment]
Hi @AndreaM2429 ! For this Issue, I have worked on the ERD to set the Associations and items corresponding to each class.
I have added User, Experience & Reservation. Thanks in advance for your feedback!

Please find attached and image of the ERD:


![Image](https://github.com/HFG43/final_capstone_back_end/assets/117187653/31be4240-369a-4416-a75e-44ebc8b31283)

**Comment by AndreaM2429** [comment]
# Status: Approved 🟢 

### Hi @HFG43  

Great work on this task, you did an excellent job, so you can close the issue 💯 🥳.

## Highlights :1st_place_medal:

- Good analysis of the topic
- Good associations between the entities

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval. Still, I would highly recommend that you consider these changes._

Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments on the issue if something is not 100% clear. Remember to tag me in your question (@AndreaM2429 ) so I can receive the notification.

**Comment by HFG43** [comment]
@AndreaM2429 Many thanks for your review!!

**Comment by HFG43** [comment]
@AndreaM2429 Hi Andre! Please find the ERD with the update of changes made on the go! The add of `name` to user, and we eliminate the user `admin` relationship with `experience



![Image](https://github.com/HFG43/final_capstone_back_end/assets/117187653/9a7a60af-0f4e-40b3-8992-d8c5b2765777)

**Comment by AndreaM2429** [comment]
# Status: ♻️ Changes Required

Hello @HFG43

You did a good job but please if you delete the relationship please also delete the line that joins the tables.

**Comment by HFG43** [comment]
Hi @AndreaM2429 ! Here it is without any line


![Image](https://github.com/HFG43/final_capstone_back_end/assets/117187653/13780c15-d3cb-4326-a551-86962dcc9b98)

**Comment by AndreaM2429** [comment]
# Status: Approved 🟢 

Hi @HFG43,

Thanks for implementing the new changes and updating the diagram, this is complete so congratulations 🥳 👏🏽 👏🏽

**Comment by HFG43** [comment]
@AndreaM2429 Please find attached an update with the image and details included in `experience`


![Image](https://github.com/HFG43/final_capstone_back_end/assets/117187653/eace5c06-d944-4d20-ab9a-75eda6086c75)
