### ISSUE TITLE
[1.5pt] - Deploy Project - Group Task

### ISSUE THREAD

**Issue by HFG43** [HFG43/final_capstone_back_end#22]
- Create `deployment` branch
- Use Heroku

**Comment by AndreaM2429** [comment]
Hello @NitBravoA92, @Dachrono & @AndreaM2429 here! 👋🏽 👋🏽 

We did the deploy of the back-end app using Render, as it is an API you can find the live documentation [here](https://gourmet-experiences.onrender.com/api-docs/index.html).

Please check the live and give us your feedback if it needed.

**Comment by NitBravoA92** [comment]
# Status: Approved :green_circle:

### Hi @AndreaM2429   👋🏽 

EXCELLENT JOB Andrea! The link is working correctly. The deployment was done successfully, the API is live now. There is nothing else to say other than it's time to close this issue 💯 🥳.

## Highlights :1st_place_medal:
- Excellent job doing the deployment of the API
- Deployment Link is not broken

## Optional suggestions
- N/A

Happy coding! :clap: :clap: :clap:

**Comment by AndreaM2429** [comment]
Thanks @NitBravoA92 for your time to checking the live
